#include "july/engine/Layout.h"

#include <array>

namespace july {

namespace {

// Generated by layoutgen from layouts/bijoy.layout:
//   inline constexpr LayoutEntry kBijoyEntries[] = { ... };
#include "july/engine/generated/BijoyLayout.inc"

using DenseTable = std::array<std::array<Token, kScanCodeCount>, kKeyLayerCount>;

consteval DenseTable buildDense() {
    DenseTable table{};
    for (const LayoutEntry& e : kBijoyEntries) {
        table[static_cast<std::size_t>(e.layer)][e.scan] = e.token;
    }
    return table;
}

constexpr DenseTable kBijoyTable = buildDense();
constexpr Token kNoToken{};

} // namespace

const Token& lookupBijoyKey(std::uint16_t scan, KeyLayer layer) noexcept {
    const auto layerIndex = static_cast<std::size_t>(layer);
    if (scan >= kScanCodeCount || layerIndex >= kKeyLayerCount) return kNoToken;
    return kBijoyTable[layerIndex][scan];
}

std::span<const LayoutEntry> bijoyLayoutEntries() noexcept {
    return kBijoyEntries;
}

} // namespace july
