<#
.SYNOPSIS
    Generates website/assets/layout.js (the key caps of the website's Bijoy keyboard) from
    layouts/bijoy.layout, so the website never shows a hand-drawn layout.
#>
$ErrorActionPreference = 'Stop'
$root = Resolve-Path (Join-Path $PSScriptRoot '..')
$source = Join-Path $root 'layouts\bijoy.layout'
$target = Join-Path $root 'website\assets\layout.js'

# Combining signs are shown on a dotted circle, as on printed Bijoy charts.
$marked = @('vowel-sign', 'vowel-sign-pre', 'modifier', 'phala', 'link')
$layerNames = @{ 'normal' = 'n'; 'shift' = 's'; 'link' = 'l'; 'link-shift' = 'ls' }

$keys = [ordered]@{}
foreach ($line in [System.IO.File]::ReadAllLines($source, [System.Text.Encoding]::UTF8)) {
    $text = ($line -split '#', 2)[0].Trim()
    if ($text -eq '') { continue }
    $fields = $text -split '\s+'
    $key, $layer, $kind = $fields[0], $fields[1], $fields[2]
    $chars = ($fields[4..($fields.Count - 1)] | ForEach-Object { [char][Convert]::ToInt32($_.Substring(2), 16) }) -join ''
    if ($marked -contains $kind) { $chars = [char]0x25CC + $chars }
    if (-not $keys.Contains($key)) { $keys[$key] = [ordered]@{} }
    $keys[$key][$layerNames[$layer]] = $chars
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// Generated by tools/Make-WebsiteLayout.ps1 from layouts/bijoy.layout. Do not edit.')
[void]$sb.AppendLine('// n = key, s = Shift, l = after g (linker), ls = after g with Shift.')
[void]$sb.Append('window.BIJOY_LAYOUT = {')
$first = $true
foreach ($k in $keys.Keys) {
    $layers = foreach ($l in $keys[$k].Keys) { '"{0}":"{1}"' -f $l, $keys[$k][$l] }
    $name = if ($k -eq '\') { '\\' } else { $k }
    [void]$sb.Append($(if ($first) { "`n" } else { ",`n" }) + ('  "{0}": {{{1}}}' -f $name, ($layers -join ',')))
    $first = $false
}
[void]$sb.AppendLine("`n};")
New-Item -ItemType Directory -Force (Split-Path $target) | Out-Null
[System.IO.File]::WriteAllText($target, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Host "Wrote $target ($($keys.Count) keys)"
