import java.io.File
import java.util.Properties
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

// The engine's tables are generated by small C++ tools that run on the build machine, so
// the native build needs a host CMake (with a host C++ compiler) besides the NDK.
// Order: -Pjuly.hostCmake, env JULY_HOST_CMAKE, july.hostCmake in local.properties,
// the CMake bundled with Visual Studio (Windows), then "cmake" on PATH.
fun hostCmake(): String {
    providers.gradleProperty("july.hostCmake").orNull?.let { return it }
    providers.environmentVariable("JULY_HOST_CMAKE").orNull?.let { return it }
    val local = rootProject.file("local.properties")
    if (local.isFile) {
        val props = Properties().apply { local.inputStream().use { load(it) } }
        props.getProperty("july.hostCmake")?.let { return it }
    }
    if (System.getProperty("os.name").startsWith("Windows")) {
        val programFiles = System.getenv("ProgramFiles(x86)") ?: "C:\\Program Files (x86)"
        val vswhere = File(programFiles, "Microsoft Visual Studio\\Installer\\vswhere.exe")
        if (vswhere.isFile) {
            val found = providers.exec {
                commandLine(
                    vswhere.path, "-latest", "-products", "*",
                    "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                    "-find", "Common7\\IDE\\CommonExtensions\\Microsoft\\CMake\\CMake\\bin\\cmake.exe",
                )
            }.standardOutput.asText.get().lineSequence().map { it.trim() }.firstOrNull { it.isNotEmpty() }
            if (found != null) return found.replace('\\', '/')
        }
    }
    return "cmake"
}

// Release signing: a properties file (storeFile, storePassword, keyAlias, keyPassword)
// kept OUTSIDE the repository, named by -Pjuly.signing, env JULY_SIGNING or july.signing in
// local.properties. Without it the release APK is built unsigned. See android/README.md.
fun signingProperties(): Properties? {
    val local = rootProject.file("local.properties").takeIf { it.isFile }
        ?.let { f -> Properties().apply { f.inputStream().use { load(it) } } }
    val path = providers.gradleProperty("july.signing").orNull
        ?: providers.environmentVariable("JULY_SIGNING").orNull
        ?: local?.getProperty("july.signing")
        ?: return null
    val file = File(path)
    if (!file.isFile) return null
    return Properties().apply { file.inputStream().use { load(it) } }
}

android {
    namespace = "org.julybangla.keyboard"

    val signing = signingProperties()
    signingConfigs {
        if (signing != null) {
            create("release") {
                storeFile = File(signing.getProperty("storeFile"))
                storePassword = signing.getProperty("storePassword")
                keyAlias = signing.getProperty("keyAlias")
                keyPassword = signing.getProperty("keyPassword")
            }
        }
    }
    compileSdk = 36
    ndkVersion = "28.2.13676358"

    defaultConfig {
        applicationId = "org.julybangla.keyboard"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0-preview"

        ndk {
            // Real phones and tablets only; x86 emulators can be added for local testing.
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }
        externalNativeBuild {
            cmake {
                arguments += listOf("-DANDROID_STL=c++_static", "-DJULY_HOST_CMAKE=${hostCmake()}")
            }
        }
    }

    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.31.6"
        }
    }

    buildTypes {
        release {
            signingConfigs.findByName("release")?.let { signingConfig = it }
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig = false
    }

    packaging {
        // Kotlin reflection metadata; the keyboard does not use reflection.
        resources.excludes += listOf("kotlin/**", "META-INF/*.version", "META-INF/*.kotlin_module")
    }
}

kotlin {
    compilerOptions {
        jvmTarget.set(JvmTarget.JVM_17)
    }
}

dependencies {
    testImplementation(libs.junit)
}
